### ISSUE TITLE
cannot find deep-gnss.yml

### ISSUE THREAD

**Issue by Aaron-WengXu** [Stanford-NavLab/deep_gnss#2]
Hey there,
Thank you for sharing your Deep GNSS codes.
I tried to run it from scratch. According to your guide, I tried to install the conda environment using conda env create -f deep-gnss.yml. But there seems to be no such a file. Should I use the environment.yml instead?

**Comment by kanhereashwin** [comment]
Yes. You should go ahead and use environment.yml instead of deep-gnss.yml
